### ISSUE TITLE
l2circuit empty but filled with "----" crashes the l2circuit parsing

### ISSUE THREAD

**Issue by lethalwp** [czerwonk/junos_exporter#106]
Hello,

When on a juniper, we configure a l2circuit that never came up, some values can be filled with "----" when the terminal-size is large enough.

example:
>show l2circuit connections brief    
Legend for interface status  
Up -- operational            
Dn -- down                   
Neighbor: 192.168.175.1 
    Interface                 Type  St     Time last up          # Up trans
    xe-0/0/2:1.45(vc 100242)  rmt   Up     May 25 18:39:56 2020           1
    xe-0/0/2:1.82(vc 110279)  rmt   HS     -----                       ----
<snip>

which gives in the junos_exporter:

2020/05/26 14:23:14 Running command on mxvpn-xxx-1: show l2circuit connections brief
2020/05/26 14:23:15 Output for mxvpn-xxx-1: <rpc-reply xmlns:junos="http://xml.juniper.net/junos/18.4R1/junos">
    <l2circuit-connection-information xmlns="http://xml.juniper.net/junos/18.4R1/junos-routing" junos:style="normal">
        <l2circuit-neighbor>
            <neighbor-address>192.168.175.1</neighbor-address>
            <connection heading="Interface                 Type  St     Time last up          # Up trans">
                <connection-id>xe-0/0/2:1.45(vc 100242)</connection-id>
                <connection-type>rmt</connection-type>
                <connection-status>Up</connection-status>
                <last-change>May 25 18:39:56 2020
                </last-change>
                <up-transitions>1</up-transitions>
            </connection>
            <connection >
                <connection-id>xe-0/0/2:1.82(vc 110279)</connection-id>
                <connection-type>rmt</connection-type>
                <connection-status>HS</connection-status>
                <last-change>-----       </last-change>
                <up-transitions>----</up-transitions>
            </connection>
        </l2circuit-neighbor>
(snip)

time="2020-05-26T14:23:15+02:00" level=error msg="L2 Circuit: strconv.ParseInt: parsing \"----\": invalid syntax" source="junos_collector.go:129"
2020/05/26 14:23:15 Running command on mxvpn-xxx-1: show ldp session

**Comment by lethalwp** [comment]
i've put the junos_exporter in debug, this is what happens:
    <l2circuit-connection-information xmlns="http://xml.juniper.net/junos/18.4R1/junos-routing" junos:style="normal">
        <l2circuit-neighbor>
            <neighbor-address>192.168.175.1</neighbor-address>
            <connection heading="Interface                 Type  St     Time last up          # Up trans">
                <connection-id>ae10.104(vc 110615)</connection-id>
                <connection-type>rmt</connection-type>
                <connection-status>HS</connection-status>
                <last-change>-----       </last-change>
                <up-transitions>----</up-transitions>
            </connection>

It can be bypassed by:
diff -u -r junos_exporter-0.9.6.orig/l2circuit/rpc.go junos_exporter-0.9.6.jys/l2circuit/rpc.go
--- junos_exporter-0.9.6.orig/l2circuit/rpc.go  2020-04-02 13:56:56.000000000 +0200
+++ junos_exporter-0.9.6.jys/l2circuit/rpc.go   2020-05-28 15:28:34.000000000 +0200
@@ -17,5 +17,5 @@
        ID           string `xml:"connection-id"`
        Type         string `xml:"connection-type"`
        StatusString string `xml:"connection-status"`
-       Transitions  int    `xml:"up-transitions,omitempty"`
+//     Transitions  int    `xml:"up-transitions,omitempty"`
 }

Since Transitions is not used atm.

**Comment by czerwonk** [comment]
Hi, thanks for the debugging effort. I removed the Transitions field, so this issue should be solved.
