### ISSUE TITLE
several interfaces have no bandwidth speed

### ISSUE THREAD

**Issue by lethalwp** [czerwonk/junos_exporter#107]
The actual "bandwidth_speed" comes from a mapping table.
- But when you build aggregates (aeXX), the bandwidth can sum up. So all values aren't available.
example:
MX> show interfaces statistics detail ae2    
Physical interface: ae2, Enabled, Physical link is Up
  Interface index: 129, SNMP ifIndex: 517, Generation: 132
  Description: XXX
  Link-level type: Ethernet, MTU: 9192, Speed: 20Gbps, BPDU Error: None, MAC-REWRITE Error: None, Loopback: Disabled, Source filtering: Disabled, Flow control: Disabled

- On newer generation mx cards, they even don't report the speed attribute anymore! so i guess it with the interface name. This doesn't work when an aggregate is built over such an interface
example:
> show interfaces statistics detail ae50 
Physical interface: ae50, Enabled, Physical link is Down, Extended Port
  Interface index: 551, SNMP ifIndex: 2166, Generation: 577
  Description: XXX
  Link-level type: Flexible-Ethernet, MTU: 9192, Speed: Unspecified, BPDU Error: None, MAC-REWRITE Error: None, Loopback: Disabled, Source filtering: Disabled, Flow control: Disabled

or on a interface:
E0> show interfaces statistics detail ge-100/0/2                  
Physical interface: ge-100/0/2, Enabled, Physical link is Up, Extended Port
  Interface index: 495, SNMP ifIndex: 66584584, Generation: 518
  Description: XXX
  Link-level type: Ethernet, MTU: 1514, MRU: 1522, LAN-PHY mode, Speed: Unspecified, Duplex: Unspecified, BPDU Error: None, Loop Detect PDU Error: None, Ethernet-Switching Error: None, MAC-REWRITE Error: None, Loopback: Disabled, Source filtering: Disabled, Flow control: Enabled, Auto-negotiation: Disabled,
  Remote fault: Online, IEEE 802.3az Energy Efficient Ethernet: Disabled, Auto-MDIX: Enabled

patch attached to limit the impact to the unknown bandwidth
It also contains the "quote" for l2circuits-int-attribute

[diffed.txt](https://github.com/czerwonk/junos_exporter/files/4695898/diffed.txt)

**Comment by czerwonk** [comment]
Patch applied. Thanks for contributing! :)
