### ISSUE TITLE
SSH user ?

### ISSUE THREAD

**Issue by AngelFreak** [czerwonk/junos_exporter#11]
What user does it use for logging into the JunOS ?
I see no option defining this, so i must assume current user ? Or root ?

My login to the JunOS device fails, manual login works with the authorized key.

A option to define the user would be great.

**Comment by czerwonk** [comment]
Hi,
you can specify the username by using the ```-ssh.user``` parameter. The default is ```junos_exporter```

**Comment by AngelFreak** [comment]
Great thanks alot!
Any chance all options will be listed in the documentation ?
