### ISSUE TITLE
Any tips for increasing performance?

### ISSUE THREAD

**Issue by mrsmeds** [czerwonk/junos_exporter#16]
First - thanks for creating junos-exporter! Scraping a single QFX5100 with default exporter configuration takes ~30 seconds. This is a huge improvement over snmp-exporter, which was 2+ minutes.

Any known configuration options on the switch to further decrease the scrape duration?

**Comment by skorpy2009** [comment]
Currently, I only see https://github.com/czerwonk/junos_exporter/issues/8 as an easy performance improvement.

**Comment by mrsmeds** [comment]
Btw, scraping actually takes 2 seconds. So all is good!

I was being dumb and using VM on my workstation to scrape switches on other side of the world. When exporter installed in same datacenter life is good.
