### ISSUE TITLE
feature request: return bgp session_status instead of session_up

### ISSUE THREAD

**Issue by 33Fraise33** [czerwonk/junos_exporter#209]
Hello,

I am trying to set alerting rules for our datacenter coreswitches with this exporter. 
i was planning to use `junos_bgp_session_up` but this is 1 if up and 0 if everything else. This unfortunately does also show as "failed" when the session is in admin down. 

The proposal is to create a new metric called `junos_bgp_session_state` which then return values for the possible states (idle, active, established, shutdown). 

Another option is to create an entry like exists for interfaces: `junos_bgp_session_error_status` which then returns 1 if operational and admin state differ.

**Comment by crabique** [comment]
This seems to have been implemented: https://github.com/czerwonk/junos_exporter/blob/c854b30193b547262ac81d501a879123e59ab65f/pkg/features/bgp/collector.go#L44

**Comment by 33Fraise33** [comment]
> This seems to have been implemented:
> 
> https://github.com/czerwonk/junos_exporter/blob/c854b30193b547262ac81d501a879123e59ab65f/pkg/features/bgp/collector.go#L44

I added them myself but I forgot to close this issue: 
https://github.com/czerwonk/junos_exporter/pull/219
