### ISSUE TITLE
v12.4 release does not contain any binary artifacts

### ISSUE THREAD

**Issue by Kilobyte22** [czerwonk/junos_exporter#252]
Up until v0.12.3 there were binary artifacts for many platforms included. With the latest release v12.4 this is not longer the case. I am assuming this was an accident, as i have not seen anything in the release notes regarding that. Can you please either add those or clarify the intention in the release notes?

Furthermore I am not sure if the version format switch was intentional, but that seems like a smaller issue to me.

**Comment by czerwonk** [comment]
Thanks for pointing that out. The version format change was not intended. It was a typo. That's also the reason the release build pipeline did not run. I created a new tag so the build artifacts should be available in the next few minutes.
