### ISSUE TITLE
[v.7] Re-enable SSH?

### ISSUE THREAD

**Issue by LaurentDumont** [czerwonk/junos_exporter#26]
Hi,

I have a tiny EX2200 that struggles with the SSH polling method. Takes about 25 seconds for a full polling cycle. Is there any way I could try the SNMP method just for testing?

Thanks!

**Comment by vishnubraj** [comment]
even me afraid of enable ssh based polling..  any chance snmp method is possible with this?

**Comment by qybl** [comment]
Hi,

imho the [snmp_exporter](https://github.com/prometheus/snmp_exporter) is a better fit if you need SNMP.
