### ISSUE TITLE
ssh user in config file

### ISSUE THREAD

**Issue by cristifalcas** [czerwonk/junos_exporter#34]
Is it possible to add the ssh user in the config file?

i tried
```
ssh:
  user: bla
user: bla
ssh.user: bla
```

All are ignored.

**Comment by AKYD** [comment]
It's not possible.

You can see the allowed values here : https://github.com/czerwonk/junos_exporter/blob/master/config/config.go

**Comment by cristifalcas** [comment]
Thank you
