### ISSUE TITLE
Multi Routing Engine Support

### ISSUE THREAD

**Issue by ashleyprimo** [czerwonk/junos_exporter#58]
I have come across a bug affecting the collection of certain metrics against targets that have multiple routing engines.

**Metrics Affected**: 
   - Storage
     - Completely incompatible with multiple routing engines. No output. (from what I have seen- may require some more testing)
   - Routing Engine Statistics
     - This works on 15.1, however, on a target running 12.3X4 these results return as 0 for all metrics. 

_It's worth noting my testing is limited due to the number of devices configured differently I have to hand to work on._ 

I believe both of these issues to be caused by the difference in XML output - as you'll see some output's depending on the setup/version of the device are nested (and do not follow the expected schema set out in the code). 

## Routing Engine Statistics Metrics
`show chassis routing-engine` output on a SRX running `12.3X48`:
```user@device1> show chassis routing-engine | display xml 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.3X48/junos">
    <multi-routing-engine-results>
        
        <multi-routing-engine-item>
            
            <re-name>node0</re-name>
            
            <route-engine-information xmlns="http://xml.juniper.net/junos/12.3X48/junos-chassis">
```

`show chassis routing-engine` output on a EX4200-24F running `15.1R5`:
```user@device2> show chassis routing-engine | display xml        
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1R5/junos">
    <route-engine-information xmlns="http://xml.juniper.net/junos/15.1R5/junos-chassis">
```

Example Output by Junos Exporter 
```# HELP junos_route_engine_memory_utilization Percentage of Routing Engine memory being used
# TYPE junos_route_engine_memory_utilization gauge
junos_route_engine_memory_utilization{target="device2"} 70
junos_route_engine_memory_utilization{target="device1"} 0
```

## Storage Metrics
`show system storage` output on a SRX running `12.3X48`:
```<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.3X48/junos">
    <multi-routing-engine-results>
        
        <multi-routing-engine-item>
            
            <re-name>node0</re-name>
            
            <system-storage-information junos:style="brief">
```

`show system storage` output on a EX4200-24F running `15.1R5`:
```<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1R5/junos">
    <multi-routing-engine-results>
        
        <multi-routing-engine-item>
            
            <re-name>fpc0</re-name>
            
            <system-storage-information junos:style="brief">
```

_Unfortunately, I do not have any Junos devices that are not in a virtual chassis._

If you'd like complete output let me know.

**Comment by czerwonk** [comment]
Thank you for pointing that out. I will have a look at it.

**Comment by czerwonk** [comment]
Parsing array now and added a label for slot

**Comment by ashleyprimo** [comment]
Perfect, thank you @czerwonk
