### ISSUE TITLE
add metrics for pem (power entry module)

### ISSUE THREAD

**Issue by soukichi** [czerwonk/junos_exporter#66]
It would be very helpful to collect pem statistics such as power consumtion, fan speed, 

 show chassis environment pem 

localre:
--------------------------------------------------------------------------
FPC 0 PEM 0 status:
  State                      Online
  Airflow                    Back to Front                           
  Temp Sensor 0                           OK   28 degrees C / 82 degrees F        
  Temp Sensor 1                           OK   33 degrees C / 91 degrees F        
  Temp Sensor 2                           OK   33 degrees C / 91 degrees F        
  Fan 0                      23680 RPM                               
  DC Output           Voltage(V) Current(A)  Power(W)  Load(%)
                        12          13            156      24     
FPC 0 PEM 1 status:
  State                      Online
  Airflow                    Back to Front                           
  Temp Sensor 0                           OK   28 degrees C / 82 degrees F        
  Temp Sensor 1                           OK   33 degrees C / 91 degrees F        
  Temp Sensor 2                           OK   32 degrees C / 89 degrees F        
  Fan 0                      23776 RPM                               
  DC Output           Voltage(V) Current(A)  Power(W)  Load(%)
                        12          14            168      25

**Comment by AKYD** [comment]
Will start working on this
