### ISSUE TITLE
asking for keyfile but I use logins in config

### ISSUE THREAD

**Issue by NosIreland** [czerwonk/junos_exporter#71]
Hi,
I'm trying to use exporter but container failing to start. I'm using config.yml and have username and password in there.

```
devices:
  - host: jun_1
    username: admin
    password: password
```

But getting error below. Looking at it, it is reading the config file as it gets host but why is it still looking for secret file? I have login details defined:

> 
> time="2019-10-23T19:57:55Z" level=info msg="Loading config from /config.yml" source="main.go:166"
> time="2019-10-23T19:57:55Z" level=fatal msg="could not initialize exporter. could not initialize config for device jun_1: could not open ssh key file: open /ssh-keyfile: no such file or directory" source="main.go:84"

**Comment by ndom91** [comment]
@NosIreland I found that if you just point it at any ssh file, it will work. It just needs something valid for that variable when starting. If you set username/password login for your devices, it will just ignore the "dummy" ssh key you entered and begin working.

**Comment by czerwonk** [comment]
Fixed the docker file: --ssh.keyfile is now empty in container by default. If anyone wants to use global key file it can still be done by using the env variable. Configuration by config file is the prefered way now.

**Comment by czerwonk** [comment]
Thanks for pointing this out! :)
