### ISSUE TITLE
Accounting section hardcoded for fpc0

### ISSUE THREAD

**Issue by bjornskovlund** [czerwonk/junos_exporter#75]
The accounting section is hardcoded for fpc0:
https://github.com/czerwonk/junos_exporter/blob/f6ee0342d7345adf44ec8c10d148783d02e6602d/accounting/collector.go#L94
https://github.com/czerwonk/junos_exporter/blob/f6ee0342d7345adf44ec8c10d148783d02e6602d/accounting/collector.go#L117

I'm unsure how discovery can be done, but at least for my usage I'm having an MS-MPC in slot 0, causing it to fail with picinfo dying on the actual router.

**Comment by czerwonk** [comment]
Hi, I will have a look in this. Thanks for reporting.

**Comment by czerwonk** [comment]
Following the JunOS documetation the fpc-slot filter is optional. So I removed it. Since i don't have a MX here I can not test the result properly. Can you please test the current master against your device. There should be metrics for every FPC installed now.
