### ISSUE TITLE
Duplicate Alarms in Red and Yellow counts

### ISSUE THREAD

**Issue by maflynn** [czerwonk/junos_exporter#96]
It looks like the alarm count may be counting some alarms twice.
When I do a show chassis alarm and a show system alarm I get the following:
![Screen Shot 2020-02-25 at 3 13 04 PM](https://user-images.githubusercontent.com/3515955/75283810-86db5280-57e1-11ea-95dc-29f3d75e4d6d.png)

However, it shows there are 5 alarms when I pull the prometheus data.
I think it should only be showing 3 alarms.
Can the list of alarms be de-duped when you count them up?

**Comment by czerwonk** [comment]
Since we do not differentiate between these two types, this is a goo idea. I will implement dedup as soon as poosible
