### ISSUE TITLE
Feature request: disable ipv6

### ISSUE THREAD

**Issue by NosIreland** [czerwonk/junos_exporter#99]
Would it be possible to make ipv6 data as an option?
It is not widely used and there is a lot of it which is just wasted space.
thanks

**Comment by arvindkonar** [comment]
I need this as well. It might be good to make ipv6 optional.

**Comment by 4xoc** [comment]
When disk space is the only concern here, you could just use Prometheus to drop the undesired timeseries at scrape time (here's a nice guide on how this can be done: https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus).
